name: python3.10-mt-vlm
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip
  - pip:
    - ipykernel
    - numpy
    - matplotlib
    - pillow
    - torch==2.6.0
    - torchvision
    - huggingface_hub
    - datasets
    - transformers
    - wandb
    - python-dotenv
    - bitsandbytes
    - unsloth
    - langchain
    - langchain_openai
    - markdown2
    - einops
    - transformers_stream_generator
    - accelerate
    - opencv-python
    - langchain-community
    - playwright
    - python-Levenshtein
    - beautifulsoup4
    - scikit-learn
    - zss
    - scipy
    - backoff
    - trl
    - flash_attn
